"""
Hallucinator Agent - AI-powered defense attorney for security alerts
"""
import sys
import os
from typing import List, Dict, Optional
from dataclasses import dataclass
import json
import random

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))


@dataclass
class DefenseContext:
    """
    Defense context generated by the Hallucinator Agent
    
    Attributes:
        justification: Benign explanation for the security alert
        confidence: Confidence score (0.0 to 1.0) in the defense
        supporting_evidence: List of evidence points supporting the defense
        risk_mitigation: Suggested actions to mitigate any remaining risk
    """
    justification: str
    confidence: float
    supporting_evidence: Optional[List[str]] = None
    risk_mitigation: Optional[str] = None


class HallucinatorAgent:
    """
    Hallucinator Agent acts as a 'Defense Attorney' for security alerts
    
    This agent uses AI to generate benign justifications for security alerts,
    helping to reduce false positives by finding legitimate explanations for
    potentially suspicious behavior.
    
    The agent analyzes:
    - The security alert details
    - User's historical behavior patterns
    - Contextual information
    
    And attempts to construct a reasonable, benign explanation.
    """
    
    def __init__(self, model: str = "gpt-4", temperature: float = 0.7):
        """
        Initialize Hallucinator Agent
        
        Args:
            model: LLM model to use (default: gpt-4)
            temperature: Temperature for LLM generation (0.0-1.0)
        """
        self.model = model
        self.temperature = temperature
    
    def generate_defense(self, alert: Dict, user_history: List[Dict]) -> DefenseContext:
        """
        Generate a benign justification for a security alert
        
        Args:
            alert: Security alert dictionary containing:
                - is_alert: Whether alert was triggered
                - risk_score: Risk score of the alert
                - reason: Reason for the alert
                - event: The event that triggered the alert
                
            user_history: List of user's historical events/behaviors
        
        Returns:
            DefenseContext with justification and confidence score
        """
        # Construct the defense attorney prompt
        prompt = self._construct_defense_prompt(alert, user_history)
        
        # Call LLM to generate defense
        llm_response = self._call_llm(prompt)
        
        # Parse the response into DefenseContext
        defense_context = self._parse_llm_response(llm_response)
        
        return defense_context
    
    def _construct_defense_prompt(self, alert: Dict, user_history: List[Dict]) -> str:
        """
        Construct the system prompt for the defense attorney LLM
        
        Args:
            alert: Security alert details
            user_history: User's historical behavior
            
        Returns:
            Formatted prompt string
        """
        # Extract alert details
        risk_score = alert.get('risk_score', 0.0)
        reason = alert.get('reason', 'Unknown reason')
        event = alert.get('event', {})
        
        # Format user history
        history_summary = self._format_user_history(user_history)
        
        # Format event details
        event_details = self._format_event(event)
        
        # Construct the prompt
        prompt = f"""You are an expert Security Defense Attorney analyzing potential false positives in security alerts.

Your role is to find BENIGN, LEGITIMATE explanations for security alerts by considering:
1. The user's normal behavior patterns
2. Business context and workflows
3. Temporal patterns (time of day, day of week)
4. System events or maintenance activities
5. Legitimate use cases that may appear suspicious

SECURITY ALERT:
Risk Score: {risk_score}/1.0
Reason: {reason}

EVENT DETAILS:
{event_details}

USER HISTORICAL BEHAVIOR:
{history_summary}

TASK:
Analyze this alert and provide a benign justification if one exists. Consider:
- Is this behavior consistent with the user's normal patterns?
- Could this be a legitimate business activity?
- Are there external factors (maintenance, system updates, deadlines) that explain this?
- What context might make this behavior reasonable?

Respond in JSON format with:
{{
    "justification": "Clear, concise benign explanation",
    "confidence": 0.0-1.0 (how confident you are in this defense),
    "supporting_evidence": ["Evidence point 1", "Evidence point 2", ...],
    "risk_mitigation": "Suggested actions to verify or mitigate any remaining risk"
}}

If you CANNOT find a reasonable benign explanation, set confidence to 0.0 and explain why the alert remains suspicious."""

        return prompt
    
    def _format_user_history(self, user_history: List[Dict]) -> str:
        """Format user history for the prompt"""
        if not user_history:
            return "No historical data available."
        
        lines = []
        for i, event in enumerate(user_history[-10:], 1):  # Last 10 events
            event_type = event.get('event_type', event.get('event', 'UNKNOWN'))
            timestamp = event.get('timestamp', 'unknown time')
            record_type = event.get('record_type', 'unknown')
            
            lines.append(f"{i}. {timestamp}: {event_type} on {record_type}")
        
        return "\n".join(lines)
    
    def _format_event(self, event: Dict) -> str:
        """Format event details for the prompt"""
        if not event:
            return "No event details available."
        
        details = []
        
        if 'user_id' in event:
            details.append(f"User: {event['user_id']}")
        if 'event_type' in event or 'event' in event:
            details.append(f"Action: {event.get('event_type', event.get('event'))}")
        if 'timestamp' in event:
            details.append(f"Time: {event['timestamp']}")
        if 'record_type' in event:
            details.append(f"Record Type: {event['record_type']}")
        if 'record_title' in event:
            details.append(f"Record: {event['record_title']}")
        if 'metadata' in event:
            details.append(f"Metadata: {json.dumps(event['metadata'])}")
        
        return "\n".join(details)
    
    def _call_llm(self, prompt: str) -> str:
        """
        Call the LLM to generate a response
        
        Args:
            prompt: The prompt to send to the LLM
            
        Returns:
            LLM response as string
        
        Note:
            This is a PLACEHOLDER implementation. In production, this should:
            1. Call the actual Aviator Model API
            2. Handle rate limiting and errors
            3. Implement retry logic
            4. Log API calls for auditing
        
        Example production implementation:
            import openai
            response = openai.ChatCompletion.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are a security defense attorney."},
                    {"role": "user", "content": prompt}
                ],
                temperature=self.temperature
            )
            return response.choices[0].message.content
        """
        # MOCK IMPLEMENTATION - Generate realistic defense responses
        
        # Simulate different types of defenses based on prompt content
        if "DELETE" in prompt and "5" in prompt:
            response = {
                "justification": "User is performing end-of-month cleanup activities. Historical data shows this user regularly performs batch deletions on the last week of each month as part of document retention policy compliance.",
                "confidence": 0.75,
                "supporting_evidence": [
                    "User has admin role with document cleanup responsibilities",
                    "Deletions occurred during business hours (9 AM - 5 PM)",
                    "Pattern matches historical end-of-month cleanup activities",
                    "All deleted items were in the 'Archive' folder marked for retention review"
                ],
                "risk_mitigation": "Verify deleted items were within user's authorized scope. Enable audit logging for all delete operations. Consider implementing soft-delete with review period."
            }
        elif "after hours" in prompt.lower() or "unusual hours" in prompt.lower():
            response = {
                "justification": "User is working remotely from different timezone or handling urgent client deliverable. Access pattern shows continuous work session, not sporadic suspicious activity.",
                "confidence": 0.65,
                "supporting_evidence": [
                    "User recently returned from international travel (timezone: GMT+8)",
                    "Calendar shows scheduled client deadline during this timeframe",
                    "Access pattern shows continuous workflow, not data exfiltration",
                    "User sent email to supervisor about working late on project"
                ],
                "risk_mitigation": "Confirm with user's manager about after-hours work authorization. Review accessed documents to ensure they align with current project scope."
            }
        elif "anomaly" in prompt.lower() or "deviation" in prompt.lower():
            response = {
                "justification": "User recently transitioned to new role with expanded responsibilities requiring access to different document types. Behavioral baseline may need updating to reflect new normal.",
                "confidence": 0.60,
                "supporting_evidence": [
                    "User promoted to senior analyst role 2 weeks ago",
                    "New role requires reviewing contracts and financial documents",
                    "Manager approved expanded access permissions last week",
                    "Accessing documents related to assigned new projects"
                ],
                "risk_mitigation": "Update user baseline profile to reflect new role responsibilities. Schedule access review with user's manager. Monitor for 30 days and adjust baselines accordingly."
            }
        elif "ADMIN" in prompt or "admin" in prompt:
            response = {
                "justification": "Unable to find sufficient benign justification. Admin-level actions require strong authorization and this event lacks supporting context.",
                "confidence": 0.15,
                "supporting_evidence": [
                    "No scheduled maintenance window documented",
                    "User's role does not typically require admin privileges",
                    "No ticket or change request found in system"
                ],
                "risk_mitigation": "Immediately verify with user and IT security team. Review all actions taken during admin session. Consider temporary access suspension pending investigation."
            }
        else:
            response = {
                "justification": "Event appears consistent with normal business operations. User's activity falls within established patterns for their role and department.",
                "confidence": 0.70,
                "supporting_evidence": [
                    "Activity matches user's job function and responsibilities",
                    "Occurred during normal business hours",
                    "No unusual access patterns detected",
                    "Similar to historical behavior for this user"
                ],
                "risk_mitigation": "Continue monitoring. No immediate action required, but maintain standard audit logging."
            }
        
        return json.dumps(response, indent=2)
    
    def _parse_llm_response(self, llm_response: str) -> DefenseContext:
        """
        Parse LLM response into DefenseContext object
        
        Args:
            llm_response: JSON string from LLM
            
        Returns:
            DefenseContext object
        """
        try:
            data = json.loads(llm_response)
            
            return DefenseContext(
                justification=data.get('justification', 'No justification provided'),
                confidence=float(data.get('confidence', 0.0)),
                supporting_evidence=data.get('supporting_evidence', []),
                risk_mitigation=data.get('risk_mitigation', 'No mitigation suggested')
            )
        except (json.JSONDecodeError, ValueError) as e:
            # Fallback if JSON parsing fails
            return DefenseContext(
                justification="Error parsing LLM response",
                confidence=0.0,
                supporting_evidence=[f"Parse error: {str(e)}"],
                risk_mitigation="Manual review required"
            )
    
    def batch_generate_defenses(self, alerts: List[Dict], user_history: Dict[str, List[Dict]]) -> List[DefenseContext]:
        """
        Generate defenses for multiple alerts
        
        Args:
            alerts: List of security alerts
            user_history: Dictionary mapping user_id to their history
            
        Returns:
            List of DefenseContext objects
        """
        defenses = []
        
        for alert in alerts:
            user_id = alert.get('event', {}).get('user_id', 'unknown')
            history = user_history.get(user_id, [])
            
            defense = self.generate_defense(alert, history)
            defenses.append(defense)
        
        return defenses
    
    def should_dismiss_alert(self, defense: DefenseContext, confidence_threshold: float = 0.7) -> bool:
        """
        Determine if alert should be dismissed based on defense confidence
        
        Args:
            defense: Defense context
            confidence_threshold: Minimum confidence to dismiss alert
            
        Returns:
            True if alert should be dismissed, False otherwise
        """
        return defense.confidence >= confidence_threshold
