"""
Sentinel Agent - AI-powered rule-based and anomaly detection for audit events
Enhanced with natural language rule processing
"""
import sys
import os
from typing import List, Dict, Optional, Any
from dataclasses import dataclass
from collections import defaultdict
from datetime import datetime
import math
import json
import re
import openai
from datetime import datetime

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))


@dataclass
class SecurityAlert:
    """
    Security alert generated by the Sentinel Agent
    
    Attributes:
        is_alert: Whether this event triggered an alert
        risk_score: Risk score from 0.0 to 1.0 (higher is riskier)
        reason: Human-readable explanation of why alert was triggered
        rule_triggered: Name of rule that was triggered (if any)
        distance_score: Euclidean distance from baseline (if applicable)
        rule_type: Type of rule ('structured', 'natural_language', 'anomaly')
    """
    is_alert: bool
    risk_score: float
    reason: str
    rule_triggered: Optional[str] = None
    distance_score: Optional[float] = None
    rule_type: Optional[str] = None


class UserProfile:
    """User behavioral profile for anomaly detection"""
    def __init__(self, user_id: str, baseline_embedding: Optional[List[float]] = None, 
                 event_counts: Optional[Dict[str, int]] = None):
        self.user_id = user_id
        self.baseline_embedding = baseline_embedding or []
        self.event_counts = event_counts or {}
        self.last_updated = None
        
        # Enhanced profiling attributes
        self.trimtype_access: Dict[str, int] = defaultdict(int)
        self.hours_active: Dict[int, int] = defaultdict(int)
        self.typical_hours: set = set()
        self.login_locations: Dict[str, int] = defaultdict(int)
        self.security_violations: int = 0
        self.total_events: int = 0
        self.event_frequency: Dict[str, float] = {}


class SentinelAgent:
    """
    Sentinel Agent forhree-pronged approach:
    1. Structured rule-based detection: Checks events against explicit security rules
    2. Natural language rules: AI-powered evaluation of admin-defined rules in human language
    3. Anomaly detection: Compares event embeddings to user behavioral baselines
    """
    
    def __init__(self, rules: List[Dict], user_profiles: Dict[str, UserProfile], 
                 api_key: Optional[str] = None, api_base: Optional[str] = None, 
                 model: str = "gpt-4", enable_ai_rules: bool = True
    
    def __init__(self, rules: List[Dict], user_profiles: Dict[str, UserProfile]):
        """
        Initialize Sentinel AgentCan be either:
                1. Structured rules (legacy format):
                   - name: Rule name/identifier
                   - condition: Condition to check (e.g., 'event_type')
                   - operator: Comparison operator ('==', '>', '<', '>=', '<=', 'in')
                   - value: Value to compare against
                   - threshold: Threshold value (for counting rules)
                   - risk_score: Risk score if rule triggers (0.0 to 1.0)
                   
                2. Natural language rules (AI-powered):
                   - name: Rule name/identifier
                   - natural_language_rule: Human language description
                   - risk_score: Risk score if rule triggers (0.0 to 1.0)
                   - enabled: Whether the rule is active (default: True)
                   
            user_profiles: Dictionary mapping user_id to UserProfile objects
            api_key: API key for LLM service
            api_base: Base URL for LLM API
            model: LLM model to use
            enable_ai_rules: Whether to enable AI-powered rule evaluation
            
        Example rules:
            [
                # Structured rule
                {
                    'name': 'Excessive Deletes',
                    'condition': 'event_type',
                    'operator': '==',
                    'value': 'DELETE',
                    'threshold': 5,
                    'risk_score': 0.8,
                    'description': 'User performed too many delete operations'
                },
                # Natural language rule
                {
                    'name': 'Suspicious After Hours Activity',
                    'natural_language_rule': 'Alert if user accesses sensitive documents between 10 PM and 6 AM on weekdays',
                    'risk_score': 0.75,
                    'enabled': True
                }
            ]
        """
        self.rules = rules
        self.user_profiles = user_profiles
        self.event_history = {}  # Track events per user for counting rules
        self.enable_ai_rules = enable_ai_rules
        
        # Initialize AI client for natural language rule processing
        if api_key and api_base and enable_ai_ any fields (dynamic structure):
                - Common fields: user_id, event_type, timestamp, etc.
                - Any custom fields from the data source
                - embedding: Vector embedding of the event (optional)
                - metadata: Additional event metadata (optional)
        
        Returns:
            SecurityAlert object with evaluation results
        """
        user_id = event.get('user_id', event.get('actor', 'unknown'))
        
        # Step 1: Check structured rules (legacy)
        rule_alert = self._check_structured_rules(event, user_id)
        if rule_alert:
            return rule_alert
        
        # Step 2: Check natural language rules (AI-powered)
        if self.use_ai and self.enable_ai_rules:
            nl_rule_alert = self._check_natural_language_rules(event, user_id)
            if nl_rule_alert:
                return nl_rule_alert
        
        # Step 3: Check anomaly detection using embeddings
        if 'embedding' in event and user_id in self.user_profiles:
            profile = self.user_profiles[user_id]
            if profile.baseline_embedding and len(profile.baseline_embedding) > 0:
                anomaly_alert = self._check_anomaly(event, profile)
                if anomaly_alert:
                    return anomaly_alert
        
        return SecurityAlert(
            is_structured_rules(self, event: Dict, user_id: str) -> Optional[SecurityAlert]:
        """
        Check event against structured security rules (legacy format)
        
        Args:
            event: Event to evaluate
            user_id: User identifier
            
        Returns:
            SecurityAlert if rule triggered, None otherwise
        """
        # Initialize event history for user if needed
        if user_id not in self.event_history:
            self.event_history[user_id] = {}
        
        event_type = event.get('event_type', event.get('event', 'UNKNOWN'))
        
        # Update event count
        if event_type not in self.event_history[user_id]:
            self.event_history[user_id][event_type] = 0
        self.event_history[user_id][event_type] += 1
        
        # Check each structured rule
        for rule in self.rules:
            # Skip natural language rules
            if 'natural_language_rule' in rule:
                continue
            
            # Check if rule is enabled
            if rule.get('enabled', True) and self._evaluate_structured_rule(rule, event, user_id):
                return SecurityAlert(
                    is_alert=True,
                    risk_score=rule.get('risk_score', 0.7),
                    reason=rule.get('description', f"Rule '{rule['name']}' triggered"),
                    rule_triggered=rule['name'],
                    rule_type='structured'ules triggered and within baseline behavior"
        )
    
    def _check_rules(self, event: Dict, user_id: str) -> Optional[SecurityAlert]:
        """
        Check event against explicit security rules
        
        Args:
            event: Event to evaluate
            user_id: User identifier
            
        Returns:
            SecurityAlert if rule triggered, None otherwise
        """
        # Initialize event history for user if needed
        if user_id not in self.event_history:
            self.event_history[user_id] = {}
        
        event_type = event.get('event_type', event.get('event', 'UNKNOWN'))
        
        # Update event count
        if event_type not in self.event_history[user_id]:
            self.event_history[user_id][event_type] = 0
        self.event_history[user_id][event_type] += 1
        
def _check_natural_language_rules(self, event: Dict, user_id: str) -> Optional[SecurityAlert]:
        """
        Check event against natural language rules using AI
        
        Args:
            event: Event to evaluate
            user_id: User identifier
            
        Returns:
            SecurityAlert if rule triggered, None otherwise
        """
        if not self.use_ai:
            return None
        
        # Get event history for context
        user_history = self.event_history.get(user_id, {})
        
        # Check each natural language rule
        for rule in self.rules:
            # Skip structured rules
            if 'natural_language_rule' not in rule:
                continue
            
            # Check if rule is enabled
            if not rule.get('enabled', True):
                continue
            
            # Evaluate using AI
            try:
                if self._evaluate_natural_language_rule(rule, event, user_id, user_history):
                    return SecurityAlert(
                        is_alert=True,
                        risk_score=rule.get('risk_score', 0.7),
                        reason=f"Natural language rule triggered: {rule['natural_language_rule']}",
                        rule_triggered=rule['name'],
                        rule_type='natural_language'
                    )
            except Exception as e:
                # Log error but continue checking other rules
                print(f"Error evaluating natural language rule '{rule['name']}': {e}")
                continue
        
        return None
    
    def _evaluate_natural_language_rule(self, rule: Dict, event: Dict, user_id: str, 
                                       user_history: Dict) -> bool:
        """
        Use AI to evaluate a natural language rule against an event
        
        Args:
            rule: Rule with natural_language_rule field
            event: Event to evaluate
            user_id: User identifier
            user_history: User's event history
            
        Returns:
            True if rule triggers, False otherwise
        """
        if not self.ai_client:
            return False
        
        # Prepare context for AI
        nl_rule = rule['natural_language_rule']
        rule_name = rule['name']
        
        # Create a clean event representation (remove embeddings)
        clean_event = {k: v for k, v in event.items() if k != 'embedding'}
        
        # Build prompt for AI
        prompt = f"""You are a security analyst evaluating an audit event against a security rule.

SECURITY RULE: {rule_name}
RULE DESCRIPTION: {nl_rule}

EVENT DATA:
{json.dumps(clean_event, indent=2, default=str)}

USER CONTEXT:
- User ID: {user_id}
- Recent event counts: {json.dumps(user_history, indent=2)}

TASK:
Analyze if this event violates the security rule. Consider:
1. Does the event match the conditions described in the rule?
2. Is the behavior suspicious based on the rule criteria?
3. Are there any contextual factors that make this event a concern?

Respond with a JSON object:
{{
    "triggers_rule": true/false,,
                rule_type='anomaly'
            )
        elif distance > self.distance_threshold_medium:
            return SecurityAlert(
                is_alert=True,
                risk_score=0.7,
                reason=f"Moderate anomaly detected: Event deviates from user baseline (distance: {distance:.2f})",
                distance_score=distance,
                rule_type='anomaly'
            )
        elif distance > self.distance_threshold_low:
            return SecurityAlert(
                is_alert=True,
                risk_score=0.4,
                reason=f"Low anomaly detected: Event slightly deviates from baseline (distance: {distance:.2f})",
                distance_score=distance,
                rule_type='anomaly'er temperature for more consistent evaluation
                max_tokens=500
            )
            
            result_text = response.choices[0].message.content.strip()
            
            # Parse JSON response
            # Handle markdown code blocks if present
            if '```json' in result_text:
                result_text = result_text.split('```json')[1].split('```')[0].strip()
            elif '```' in result_text:
                result_text = result_text.split('```')[1].split('```')[0].strip()
            
            result = json.loads(result_text)
            
            # Rule triggers if AI says so and confidence is reasonable
            return result.get('triggers_rule', False) and result.get('confidence', 0) >= 0.6
            
        except Exception as e:
            print(f"Error in AI rule evaluation: {e}")
            return False
    
    def _evaluate_structured_rule(self, rule: Dict, event: Dict, user_id: str) -> bool:
        """
        Evaluate a single structured rule against an event with dynamic field access
        
        Args:
            rule: Rule dictionary
            event: Event to check
            user_id: User identifier
            
        Returns:
            True if rule triggers, False otherwise
        """
        Add a new rule to the agent (structured or natural language)
        
        Args:
            rule: Rule dictionary with either structured format or natural_language_rule
        """
        self.rules.append(rule)
    
    def add_natural_language_rule(self, name: str, description: str, risk_score: float = 0.7):
        """
        Add a new natural language rule from admin input
        
        Args:
            name: Rule name
            description: Human language description of the rule
            risk_score: Risk score if rule triggers (0.0 to 1.0)
        """
        rule = {
            'name': name,
            'natural_language_rule': description,
            'risk_score': risk_score,
            'enabled': True,
            'created_at': datetime.now().isoformat()
        }
        self.rules.append(rule)
        return rule
    
    def remove_rule(self, rule_name: str):
        """Remove a rule by name"""
        self.rules = [r for r in self.rules if r.get('name') != rule_name]
    
    def update_rule(self, rule_name: str, updates: Dict):
        """
        Update an existing rule
        
        Args:
            rule_name: Name of rule to update
            updates: Dictionary of fields to update
        """
        for rule in self.rules:
            if rule.get('name') == rule_name:
                rule.update(updates)
                break
    
    def enable_rule(self, rule_name: str):
        """Enable a rule"""
        self.update_rule(rule_name, {'enabled': True})
    
    def disable_rule(self, rule_name: str):
        """Disable a rule"""
        self.update_rule(rule_name, {'enabled': False})
    
    def get_rules(self, rule_type: Optional[str] = None) -> List[Dict]:
        """
        Get all rules, optionally filtered by type
        
        Args:
            rule_type: 'structured', 'natural_language', or None for all
            
        Returns:
            List of rules
        """
        if rule_type == 'structured':
            return [r for r in self.rules if 'natural_language_rule' not in r]
        elif rule_type == 'natural_language':
            return [r for r in self.rules if 'natural_language_rule' in r]
        else:
            return self.rules
        # Dynamically get the actual value from event using dot notation
        actual_value = self._get_nested_value(event, condition)
        
        # Special handling for time-based conditions
        if condition == 'hour' or 'hour' in str(condition).lower():
            actual_value = self._extract_hour(event)
        
        if actual_value is None:
            return False
        
        # Apply operator
        matches = self._apply_operator(actual_value, operator, expected_value)
        
        # If threshold is specified, check event count
        if threshold is not None and matches:
            event_type = str(actual_value)
            event_count = self.event_history[user_id].get(event_type, 0)
            return event_count > threshold
        
        return matches
    
    def _get_nested_value(self, data: Dict, path: str) -> Any:
        """
        Get value from nested dictionary using dot notation
        
        Args:
            data: Dictionary to search
            path: Dot-separated path (e.g., 'metadata.ip_address' or 'event_type')
            
        Returns:
            Value at path, or None if not found
        """
        if not path:
            return None
        
        # Handle direct access
        if '.' not in path:
            # Try multiple common field name variations
            for key in [path, path.lower(), path.upper()]:
                if key in data:
                    return data[key]
            # Try alternatives like 'event' for 'event_type'
            if path == 'event_type' and 'event' in data:
                return data['event']
            if path == 'user_id' and 'actor' in data:
                return data['actor']
            return None
        
        # Handle nested access
        keys = path.split('.')
        current = data
        
        for key in keys:
            if isinstance(current, dict):
                current = current.get(key)
                if current is None:
                    return None
            else:
                return None
        
        return current
    
    def _extract_hour(self, event: Dict) -> Optional[int]:
        """
        Extract hour from timestamp in event
        
        Args:
            event: Event dictionary
            
        Returns:
            Hour (0-23) or None
        """
        timestamp = event.get('timestamp', '')
        
        if not timestamp:
            return None
        
        try:
            # Handle ISO format
            if isinstance(timestamp, str):
                if 'T' in timestamp:
                    time_part = timestamp.split('T')[1]
                    hour = int(time_part.split(':')[0])
                    return hour
            # Handle datetime object
            elif hasattr(timestamp, 'hour'):
                return timestamp.hour
        except (ValueError, IndexError, AttributeError):
            pass
        
        return None
    
    def _apply_operator(self, actual: Any, operator: str, expected: Any) -> bool:
        """
        Apply comparison operator dynamically
        
        Args:
            actual: Actual value from event
            operator: Comparison operator
            expected: Expected value from rule
            
        Returns:
            True if comparison passes, False otherwise
        """
        try:
            if operator == '==':
                return actual == expected
            elif operator == '!=':
                return actual != expected
            elif operator == '>':
                return float(actual) > float(expected)
            elif operator == '<':
                return float(actual) < float(expected)
            elif operator == '>=':
                return float(actual) >= float(expected)
            elif operator == '<=':
                return float(actual) <= float(expected)
            elif operator == 'in':
                return actual in expected
            elif operator == 'not in':
                return actual not in expected
            elif operator == 'contains':
                return expected in str(actual)
            elif operator == 'startswith':
                return str(actual).startswith(str(expected))
            elif operator == 'endswith':
                return str(actual).endswith(str(expected))
            elif operator == 'regex':
                return bool(re.search(expected, str(actual)))
            else:
                return False
        except (ValueError, TypeError, AttributeError):
            return False== '<=':
            matches = actual_value <= expected_value
        elif operator == 'in':
            matches = actual_value in expected_value
        else:
            return False
        
        if threshold is not None and matches:
            event_count = self.event_history[user_id].get(actual_value, 0)
            return event_count > threshold
        
        return matches
    
    def _check_anomaly(self, event: Dict, profile: UserProfile) -> Optional[SecurityAlert]:
        """Check for anomalies using embedding distance"""
        event_embedding = event.get('embedding', [])
        baseline_embedding = profile.baseline_embedding
        
        if not event_embedding or not baseline_embedding:
            return None
        
        distance = self._euclidean_distance(event_embedding, baseline_embedding)
        
        if distance > self.distance_threshold_high:
            return SecurityAlert(
                is_alert=True,
                risk_score=0.9,
                reason=f"High anomaly detected: Event significantly deviates from user baseline (distance: {distance:.2f})",
                distance_score=distance
            )
        elif distance > self.distance_threshold_medium:
            return SecurityAlert(
                is_alert=True,
                risk_score=0.7,
                reason=f"Moderate anomaly detected: Event deviates from user baseline (distance: {distance:.2f})",
                distance_score=distance
            )
        elif distance > self.distance_threshold_low:
            return SecurityAlert(
                is_alert=True,
                risk_score=0.4,
                reason=f"Low anomaly detected: Event slightly deviates from baseline (distance: {distance:.2f})",
                distance_score=distance
            )
        
        return None
    
    @staticmethod
    def _euclidean_distance(vec1: List[float], vec2: List[float]) -> float:
        """Calculate Euclidean distance between two vectors"""
        if len(vec1) != len(vec2):
            raise ValueError(f"Vectors must have same length: {len(vec1)} != {len(vec2)}")
        
        sum_squares = sum((a - b) ** 2 for a, b in zip(vec1, vec2))
        return math.sqrt(sum_squares)
    
    def reset_event_history(self, user_id: Optional[str] = None):
        """Reset event history for user or all users"""
        if user_id:
            self.event_history[user_id] = {}
        else:
            self.event_history = {}
    
    def add_rule(self, rule: Dict):
        """Add a new rule to the agent"""
        self.rules.append(rule)
    
    def remove_rule(self, rule_name: str) -> bool:
        """Remove rule by name"""
        initial_count = len(self.rules)
        self.rules = [r for r in self.rules if r.get('name') != rule_name]
        return len(self.rules) < initial_count
    
    def remove_rule_by_index(self, index: int) -> bool:
        """Remove rule by index"""
        if 0 <= index < len(self.rules):
            self.rules.pop(index)
            return True
        return False
    
    def clear_all_rules(self) -> int:
        """Remove all rules and return count"""
        count = len(self.rules)
        self.rules = []
        return count
    
    def get_user_profile(self, user_id: str) -> Optional[UserProfile]:
        """Get user profile by ID"""
        return self.user_profiles.get(user_id)
    
    def update_user_profile(self, user_id: str, profile: UserProfile):
        """Update or add a user profile"""
        self.user_profiles[user_id] = profile
    
    def _extract_user_id(self, event: Dict) -> str:
        """Extract user ID from event"""
        if 'user_id' in event:
            return event['user_id']
        description = event.get('HistoryEventDescription', {}).get('Value', '')
        if "done by '" in description:
            start = description.index("done by '") + len("done by '")
            end = description.index("'", start)
            user_id = description[start:end]
            if '\\' in user_id:
                user_id = user_id.split('\\')[1]
            return user_id
        login_location = event.get('HistoryLoginLocation', {}).get('NameString', '')
        return login_location if login_location else 'unknown'
    
    def train_profile_from_events(self, user_id: str, training_events: List[Dict]):
        """Train or update user profile from historical events"""
        if user_id not in self.user_profiles:
            self.user_profiles[user_id] = UserProfile(user_id)
        profile = self.user_profiles[user_id]
        for event in training_events:
            self._update_profile_with_event(profile, event)
        self._finalize_profile_training(profile)
    
    def _update_profile_with_event(self, profile: UserProfile, event: Dict):
        """Update profile with single event"""
        profile.total_events += 1
        event_type = event.get('event_type') or event.get('HistoryEventType', {}).get('Value', 'Unknown')
        profile.event_counts[event_type] = profile.event_counts.get(event_type, 0) + 1
        trim_type = event.get('HistoryForObjectType', {}).get('Value')
        if trim_type:
            profile.trimtype_access[trim_type] += 1
        
        timestamp_str = event.get('timestamp') or event.get('HistoryDoneOn', {}).get('DateTime', '')
        if timestamp_str:
            try:
                dt = datetime.fromisoformat(timestamp_str.replace('Z', '+00:00'))
                profile.hours_active[dt.hour] += 1
            except:
                pass
        login_location = event.get('HistoryLoginLocation', {}).get('NameString', '')
        if login_location:
            profile.login_locations[login_location] += 1
        
        if event.get('HistoryIsSecurityViolation', {}).get('Value', False):
            profile.security_violations += 1
    
    def _finalize_profile_training(self, profile: UserProfile):
        """Calculate final profile statistics after training"""
        # Calculate typical working hours (hours with >10% of activity)
        if profile.hours_active:
            total_hour_events = sum(profile.hours_active.values())
            threshold = total_hour_events * 0.1
            profile.typical_hours = {h for h, count in profile.hours_active.items() if count >= threshold}
    
    def _check_enhanced_anomalies(self, event: Dict, user_id: str) -> Optional[SecurityAlert]:
        """Check for behavioral anomalies"""
        profile = self.user_profiles[user_id]
        if profile.total_events < 20:
            return None
        
        anomalies = []
        max_severity = 0.0
        
        event_type = event.get('event_type') or event.get('HistoryEventType', {}).get('Value', 'Unknown')
        if event_type not in profile.event_counts and profile.total_events > 50:
            anomalies.append(f"New event type '{event_type}'")
            max_severity = max(max_severity, 0.6)
        trim_type = event.get('HistoryForObjectType', {}).get('Value')
        if trim_type and trim_type not in profile.trimtype_access and profile.total_events > 50:
            anomalies.append(f"New object type '{trim_type}'")
            max_severity = max(max_severity, 0.5)
        
        timestamp_str = event.get('timestamp') or event.get('HistoryDoneOn', {}).get('DateTime', '')
        if timestamp_str and profile.typical_hours:
            try:
                dt = datetime.fromisoformat(timestamp_str.replace('Z', '+00:00'))
                if dt.hour not in profile.typical_hours:
                    anomalies.append(f"Unusual hour {dt.hour}:00")
                    max_severity = max(max_severity, 0.7)
            except:
                pass
        
        login_location = event.get('HistoryLoginLocation', {}).get('NameString', '')
        if login_location and login_location not in profile.login_locations and profile.total_events > 20:
            anomalies.append(f"New location '{login_location}'")
            max_severity = max(max_severity, 0.8)
        
        if event_type in profile.event_frequency:
            frequency = profile.event_frequency[event_type]
            if frequency < 0.01 and profile.total_events > 50:
                anomalies.append(f"Rare event type '{event_type}' (occurs {frequency*100:.1f}% of time)")
                severity = min(0.95, 0.7 + (1 - frequency) * 0.25)
                max_severity = max(max_severity, severity)
        
        event_keywords_high_risk = ['delete', 'remove', 'permission', 'acl', 'access', 'bypass', 'security', 'admin', 'privilege', 'grant', 'revoke']
        event_lower = event_type.lower()
        if any(keyword in event_lower for keyword in event_keywords_high_risk):
            if event_type not in profile.event_counts or profile.event_counts[event_type] < 3:
                anomalies.append(f"Sensitive operation '{event_type}' (rarely performed)")
                max_severity = max(max_severity, 0.85)
        
        if event.get('HistoryIsSecurityViolation', {}).get('Value', False):
            anomalies.append("Security violation flag set")
            max_severity = max(max_severity, 0.95)
        
        if anomalies:
            reason = f"User '{user_id}' behavioral anomalies detected:\n" + "\n".join(f"  • {a}" for a in anomalies)
            return SecurityAlert(
                is_alert=True,
                risk_score=max_severity,
                reason=reason,
                rule_triggered="Enhanced Behavioral Analysis"
            )
        
        return None
    
    def add_rule_from_natural_language(self, natural_language_rule: str) -> Dict:
        """Convert natural language rule to structured format using AI"""
        if not self.ai_enabled:
            raise RuntimeError("AI is not enabled. Provide api_key, api_base, and model to use natural language rules.")
        
        conversion_prompt = f"""Convert this security rule to JSON:
"{natural_language_rule}"

JSON fields: name, condition, operator, value, threshold (optional), time_window (optional), risk_score (0-1), description, severity (CRITICAL/HIGH/MEDIUM/LOW).

Examples:
"Delete >10 files in 1 hour" → {{"name":"Excessive Deletes","condition":"event_type","operator":"==","value":"DELETE","threshold":10,"time_window":60,"risk_score":0.8,"description":"User deleted >10 files in 1 hour","severity":"HIGH"}}
"Access after 6pm" → {{"name":"After Hours Access","condition":"hour","operator":">=","value":18,"risk_score":0.7,"description":"Access after 6pm","severity":"MEDIUM"}}

Return JSON only, no explanation."""

        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": "Convert security rules to JSON. Return only valid JSON."},
                {"role": "user", "content": conversion_prompt}
            ],
            response_format={"type": "json_object"},
            temperature=0.3
        )
        rule = json.loads(response.choices[0].message.content)
        self.rules.append(rule)
        return rule
    
    def get_rules(self) -> List[Dict]:
        """Get all active rules"""
        return self.rules.copy()
    
    def get_rule_summary(self) -> List[Dict]:
        """Get summary of all rules"""
        summaries = []
        for idx, rule in enumerate(self.rules):
            summaries.append({
                'index': idx,
                'name': rule.get('name', 'Unnamed Rule'),
                'severity': rule.get('severity', 'MEDIUM'),
                'risk_score': rule.get('risk_score', 0.5),
                'description': rule.get('description', 'No description'),
                'condition': rule.get('condition', 'unknown'),
                'value': rule.get('value', 'unknown')
            })
        return summaries
    
    def find_rules_by_name(self, search_term: str) -> List[Dict]:
        """Find rules by name (case-insensitive)"""
        search_lower = search_term.lower()
        return [r for r in self.rules if search_lower in r.get('name', '').lower()]
    
    def import_rules_from_list(self, natural_language_rules: List[str]) -> List[Dict]:
        """Convert multiple NL rules at once"""
        converted_rules = []
        for nl_rule in natural_language_rules:
            try:
                rule = self.add_rule_from_natural_language(nl_rule)
                converted_rules.append(rule)
            except Exception as e:
                pass
        return converted_rules
    
    def export_rules_for_ai_agent(self) -> List[Dict]:
        """Export rules for AI agent"""
        return self.get_rules()
    
    def sync_rules_to_ai_agent(self, sentinel_agent):
        """Sync admin rules to AI sentinel agent"""
        rules = self.export_rules_for_ai_agent()
        sentinel_agent.set_custom_rules(rules)
        """
        Synchronize admin rules to sentinel_agent for AI-based detection
        
        Args:
            sentinel_agent: Instance of SentinelAgent from sentinel_agent.py
            
        Usage:
            # Admin defines rules in natural language
            sentinel.add_rule_from_natural_language(
                "Alert if user deletes more than 5 records in 10 minutes"
            )
            
            # Sync rules to AI agent
            sentinel.sync_rules_to_ai_agent(ai_sentinel_agent)
            
            # Now AI agent will respect admin rules in analysis
        """
        rules = self.export_rules_for_ai_agent()
        sentinel_agent.set_custom_rules(rules)
        print(f"✓ Synced {len(rules)} admin rule(s) to AI sentinel agent")
