"""
Sentinel Agent - Rule-based and anomaly detection for audit events
"""
import sys
import os
from typing import List, Dict, Optional
from dataclasses import dataclass
import math

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))


@dataclass
class SecurityAlert:
    """
    Security alert generated by the Sentinel Agent
    
    Attributes:
        is_alert: Whether this event triggered an alert
        risk_score: Risk score from 0.0 to 1.0 (higher is riskier)
        reason: Human-readable explanation of why alert was triggered
        rule_triggered: Name of rule that was triggered (if any)
        distance_score: Euclidean distance from baseline (if applicable)
    """
    is_alert: bool
    risk_score: float
    reason: str
    rule_triggered: Optional[str] = None
    distance_score: Optional[float] = None


class UserProfile:
    """
    User profile containing behavioral baseline
    
    Attributes:
        user_id: User identifier
        baseline_embedding: Average embedding vector representing normal behavior
        event_counts: Dictionary of event type counts
        last_updated: Timestamp of last profile update
    """
    def __init__(self, user_id: str, baseline_embedding: Optional[List[float]] = None, 
                 event_counts: Optional[Dict[str, int]] = None):
        self.user_id = user_id
        self.baseline_embedding = baseline_embedding or []
        self.event_counts = event_counts or {}
        self.last_updated = None


class SentinelAgent:
    """
    Sentinel Agent for evaluating security events using rules and anomaly detection
    
    The agent uses a two-pronged approach:
    1. Rule-based detection: Checks events against explicit security rules
    2. Anomaly detection: Compares event embeddings to user behavioral baselines
    """
    
    def __init__(self, rules: List[Dict], user_profiles: Dict[str, UserProfile]):
        """
        Initialize Sentinel Agent
        
        Args:
            rules: List of rule dictionaries. Each rule should have:
                - name: Rule name/identifier
                - condition: Condition to check (e.g., 'event_type')
                - operator: Comparison operator ('==', '>', '<', '>=', '<=', 'in')
                - value: Value to compare against
                - threshold: Threshold value (for counting rules)
                - risk_score: Risk score if rule triggers (0.0 to 1.0)
                
            user_profiles: Dictionary mapping user_id to UserProfile objects
            
        Example rules:
            [
                {
                    'name': 'Excessive Deletes',
                    'condition': 'event_type',
                    'operator': '==',
                    'value': 'DELETE',
                    'threshold': 5,
                    'risk_score': 0.8,
                    'description': 'User performed too many delete operations'
                },
                {
                    'name': 'After Hours Access',
                    'condition': 'hour',
                    'operator': 'in',
                    'value': [0, 1, 2, 3, 4, 5, 22, 23],
                    'risk_score': 0.6,
                    'description': 'Access during unusual hours'
                }
            ]
        """
        self.rules = rules
        self.user_profiles = user_profiles
        self.event_history = {}  # Track events per user for counting rules
        
        # Thresholds for anomaly detection
        self.distance_threshold_low = 0.5
        self.distance_threshold_medium = 1.0
        self.distance_threshold_high = 2.0
    
    def evaluate_event(self, event: Dict) -> SecurityAlert:
        """
        Evaluate a security event using rules and anomaly detection
        
        Args:
            event: Event dictionary containing:
                - user_id: User who performed the action
                - event_type: Type of event (READ, WRITE, DELETE, etc.)
                - embedding: Vector embedding of the event (optional)
                - timestamp: Event timestamp
                - metadata: Additional event metadata
        
        Returns:
            SecurityAlert object with evaluation results
        """
        user_id = event.get('user_id', 'unknown')
        
        # Step 1: Check explicit rules
        rule_alert = self._check_rules(event, user_id)
        if rule_alert:
            return rule_alert
        
        # Step 2: Check anomaly detection using embeddings
        if 'embedding' in event and user_id in self.user_profiles:
            profile = self.user_profiles[user_id]
            
            if profile.baseline_embedding and len(profile.baseline_embedding) > 0:
                anomaly_alert = self._check_anomaly(event, profile)
                if anomaly_alert:
                    return anomaly_alert
        
        # No alert triggered
        return SecurityAlert(
            is_alert=False,
            risk_score=0.0,
            reason="Event appears normal - no rules triggered and within baseline behavior"
        )
    
    def _check_rules(self, event: Dict, user_id: str) -> Optional[SecurityAlert]:
        """
        Check event against explicit security rules
        
        Args:
            event: Event to evaluate
            user_id: User identifier
            
        Returns:
            SecurityAlert if rule triggered, None otherwise
        """
        # Initialize event history for user if needed
        if user_id not in self.event_history:
            self.event_history[user_id] = {}
        
        event_type = event.get('event_type', event.get('event', 'UNKNOWN'))
        
        # Update event count
        if event_type not in self.event_history[user_id]:
            self.event_history[user_id][event_type] = 0
        self.event_history[user_id][event_type] += 1
        
        # Check each rule
        for rule in self.rules:
            if self._evaluate_rule(rule, event, user_id):
                return SecurityAlert(
                    is_alert=True,
                    risk_score=rule.get('risk_score', 0.7),
                    reason=rule.get('description', f"Rule '{rule['name']}' triggered"),
                    rule_triggered=rule['name']
                )
        
        return None
    
    def _evaluate_rule(self, rule: Dict, event: Dict, user_id: str) -> bool:
        """
        Evaluate a single rule against an event
        
        Args:
            rule: Rule dictionary
            event: Event to check
            user_id: User identifier
            
        Returns:
            True if rule triggers, False otherwise
        """
        condition = rule.get('condition')
        operator = rule.get('operator')
        expected_value = rule.get('value')
        threshold = rule.get('threshold')
        
        # Get the actual value from event
        if condition == 'event_type':
            actual_value = event.get('event_type', event.get('event'))
        elif condition == 'hour':
            # Extract hour from timestamp
            timestamp = event.get('timestamp', '')
            if isinstance(timestamp, str) and 'T' in timestamp:
                time_part = timestamp.split('T')[1]
                actual_value = int(time_part.split(':')[0])
            else:
                return False
        else:
            actual_value = event.get(condition)
        
        # Apply operator
        if operator == '==':
            matches = actual_value == expected_value
        elif operator == '!=':
            matches = actual_value != expected_value
        elif operator == '>':
            matches = actual_value > expected_value
        elif operator == '<':
            matches = actual_value < expected_value
        elif operator == '>=':
            matches = actual_value >= expected_value
        elif operator == '<=':
            matches = actual_value <= expected_value
        elif operator == 'in':
            matches = actual_value in expected_value
        else:
            return False
        
        # If threshold is specified, check event count
        if threshold is not None and matches:
            event_count = self.event_history[user_id].get(actual_value, 0)
            return event_count > threshold
        
        return matches
    
    def _check_anomaly(self, event: Dict, profile: UserProfile) -> Optional[SecurityAlert]:
        """
        Check for anomalous behavior using embedding distance
        
        Args:
            event: Event with embedding
            profile: User profile with baseline embedding
            
        Returns:
            SecurityAlert if anomaly detected, None otherwise
        """
        event_embedding = event.get('embedding', [])
        baseline_embedding = profile.baseline_embedding
        
        if not event_embedding or not baseline_embedding:
            return None
        
        # Calculate Euclidean distance
        distance = self._euclidean_distance(event_embedding, baseline_embedding)
        
        # Determine alert level based on distance thresholds
        if distance > self.distance_threshold_high:
            return SecurityAlert(
                is_alert=True,
                risk_score=0.9,
                reason=f"High anomaly detected: Event significantly deviates from user baseline (distance: {distance:.2f})",
                distance_score=distance
            )
        elif distance > self.distance_threshold_medium:
            return SecurityAlert(
                is_alert=True,
                risk_score=0.7,
                reason=f"Moderate anomaly detected: Event deviates from user baseline (distance: {distance:.2f})",
                distance_score=distance
            )
        elif distance > self.distance_threshold_low:
            return SecurityAlert(
                is_alert=True,
                risk_score=0.4,
                reason=f"Low anomaly detected: Event slightly deviates from baseline (distance: {distance:.2f})",
                distance_score=distance
            )
        
        return None
    
    @staticmethod
    def _euclidean_distance(vec1: List[float], vec2: List[float]) -> float:
        """
        Calculate Euclidean distance between two vectors
        
        Args:
            vec1: First vector
            vec2: Second vector
            
        Returns:
            Euclidean distance
        """
        if len(vec1) != len(vec2):
            raise ValueError(f"Vectors must have same length: {len(vec1)} != {len(vec2)}")
        
        sum_squares = sum((a - b) ** 2 for a, b in zip(vec1, vec2))
        return math.sqrt(sum_squares)
    
    def reset_event_history(self, user_id: Optional[str] = None):
        """
        Reset event history for a user or all users
        
        Args:
            user_id: User to reset, or None to reset all
        """
        if user_id:
            self.event_history[user_id] = {}
        else:
            self.event_history = {}
    
    def add_rule(self, rule: Dict):
        """Add a new rule to the agent"""
        self.rules.append(rule)
    
    def remove_rule(self, rule_name: str):
        """Remove a rule by name"""
        self.rules = [r for r in self.rules if r.get('name') != rule_name]
    
    def get_user_profile(self, user_id: str) -> Optional[UserProfile]:
        """Get user profile by ID"""
        return self.user_profiles.get(user_id)
    
    def update_user_profile(self, user_id: str, profile: UserProfile):
        """Update or add a user profile"""
        self.user_profiles[user_id] = profile
